project = "IBB-3D"
model_folder = "\\app\\data\\Martin-Data\\IBB-3D\\IBB-2D-TS-2025-11-13"
nesting = 1
video_extension = "avi"
path = "/app/data/Martin-Data/IBB-3D"
converted_video_speed = 1
model_type = "deeplabcut"

[pipeline]
videos_raw = "videos-raw"
pose_2d = "pose-2d"
videos_raw_mp4 = "videos-raw-mp4"
pose_2d_filter = "pose-2d-filtered"
pose_2d_projected = "pose-2d-proj"
pose_3d = "pose-3d"
pose_3d_filter = "pose-3d-filtered"
videos_labeled_2d = "videos-labeled"
videos_labeled_2d_filter = "videos-labeled-filtered"
calibration_videos = "calibration"
calibration_results = "calibration"
videos_labeled_3d = "videos-3d"
videos_labeled_3d_filter = "videos-3d-filtered"
angles = "angles"
summaries = "summaries"
videos_combined = "videos-combined"
videos_compare = "videos-compare"
videos_2d_projected = "videos-2d-proj"

[calibration]
board_type = "charuco"
board_size = [ 8, 5,]
board_marker_bits = 4
board_marker_dict_number = 50
board_marker_length = 3
board_square_side_length = 5
animal_calibration = false
fisheye = false

[triangulation]
cam_regex = "cam([0-9])"
ransac = false
optim = false
scale_smooth = 2
scale_length = 2
scale_length_weak = 1
reproj_error_threshold = 5
score_threshold = 0.8
n_deriv_smooth = 3
constraints = []
constraints_weak = []
optim_chunking = false
optim_chunking_size = 1000

[labeling]
scheme = [ [ "R-Wrist", "R-D2Base", "R-D2Mid",], [ "R-Wrist", "R-D3Base", "R-D3Mid",], [ "R-Wrist", "R-D4Base", "R-D4Mid",], [ "L-Wrist", "L-D2Base", "L-D2Mid",], [ "L-Wrist", "L-D3Base", "L-D3Mid",], [ "L-Wrist", "L-D4Base", "L-D4Mid",],]

[manual_verification]
manually_verify = false

[filter]
enabled = false
type = "medfilt"
medfilt = 13
offset_threshold = 25
score_threshold = 0.05
spline = true
n_back = 5
multiprocessing = false

[filter3d]
enabled = false
medfilt = 17
offset_threshold = 15
